# Generated by Django 5.1.6 on 2026-03-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Product category', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='emoji',
            field=models.CharField(blank=True, help_text='Emoji icon for the product', max_length=10),
        ),
    ]
