# Generated by Django 5.1.6 on 2026-03-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a product photo (shown on the storefront).', null=True, upload_to='product_images/%Y/%m/'),
        ),
    ]
