# Generated by Django 5.1.6 on 2026-03-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Personal Care', 'Personal Care'), ('Accessories', 'Accessories'), ('Kitchen', 'Kitchen'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Fitness', 'Fitness'), ('Stationery', 'Stationery'), ('Home & Garden', 'Home & Garden')], default='General', help_text='Used for storefront filters.', max_length=100),
        ),
    ]
